/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kdt_y_be_toy_project1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    
}
