/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kdt_y_be_toy_project1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
